[package]
name = "mmedit"
version = "11.0.1"
edition = "2018"

[dependencies]
measureme = { path = "../measureme" }
decodeme = { path = "../decodeme" }
clap = { version = "4.5.0", features = ["derive"] }
